version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://database:1433;databaseName=taskmanager;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: T@skmanager123
    networks:
      - mynetwork

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "T@skmanager123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P T@skmanager123" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  mynetwork:
    driver: bridge

volumes:
  sqlserverdata: