services:
  app:
    container_name: taskmanagerapi
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=taskmanager;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: T@skmanager123
    networks:
      - mynetwork

  db:
    container_name: sqlserver
    build: ./db
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT name FROM sys.databases WHERE name = ''taskmanager'';' | /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P T@skmanager123 -C -d master -h -1 -W" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge